nginx:
  image: nginx:stable-alpine
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/services.d:/etc/nginx/services.d:ro
    - ./nginx/server.crt:/etc/nginx/server.crt:ro
    - ./nginx/server.key:/etc/nginx/server.key:ro
  links:
    - geneinfo
    - gene2pheno
    - genomebuild
    - hpo
    - coverage
    - bambinner
    - bamreaddepther
    - bamstatsalive
    - vcfstatsalive
    - genecoverage
    - knownvariants
    - od_samtools
    - samtools
    - bcftools
    - freebayes
    - vcflib
    - vt
    - od_tabix
    - tabix
    - vcfdepther
    - af
    - vep
    - phenolyzer

geneinfo:
  image: qiaoy/iobio.geneinfo:v2.3.1
  volumes:
    - ./data-vol/geneinfo:/home/iobio/workdir/geneinfo:ro
gene2pheno:
  image: qiaoy/iobio.gene2pheno:v1.0
  volumes:
    - ./data-vol/gene2pheno:/home/iobio/workdir/gene2pheno:ro
genomebuild:
  image: qiaoy/iobio.genomebuild:v2.3
  volumes:
    - ./data-vol/genomebuild:/home/iobio/workdir/genomebuild:ro
hpo:
  image: qiaoy/iobio.hpo:v1.0
  volumes:
    - ./data-vol/hpo:/home/iobio/workdir/hpo:ro
coverage:
  image: qiaoy/iobio.coverage:v2.4
bambinner:
  image: qiaoy/iobio.bambinner:v2.3
bamreaddepther:
  image: qiaoy/iobio.bamreaddepther:v2.4
bamstatsalive:
  image: qiaoy/iobio.bamstatsalive:v2.3
vcfstatsalive:
  image: qiaoy/iobio.vcfstatsalive:v2.4
genecoverage:
  image: qiaoy/iobio.genecoverage:v2.3
knownvariants:
  image: qiaoy/iobio.knownvariants:v2.3
od_samtools:
  image: qiaoy/iobio.samtools_od:v2.3.4
samtools:
  image: qiaoy/iobio.samtools:v2.3.3
bcftools:
  image: qiaoy/iobio.bcftools:v2.3
freebayes:
  image: qiaoy/iobio.freebayes:v2.3
    - ./data-vol/data:/home/iobio/workdir/data:ro
vcflib:
  image: qiaoy/iobio.vcflib:v2.3
vt:
  image: qiaoy/iobio.vt:v2.3
  volumes:
    - ./data-vol/data:/home/iobio/workdir/data:ro
od_tabix:
  image: qiaoy/iobio.tabix_od:v2.3.3
tabix:
  image: qiaoy/iobio.tabix:v2.3.1
vcfdepther:
  image: qiaoy/iobio.vcfdepther:v2.3
af:
  image: qiaoy/iobio.af:v2.3.1
  volumes:
    - ./data-vol/afdata:/home/iobio/workdir/afdata:ro
vep:
  image: qiaoy/iobio.vep:v2.4.1
  volumes:
    - ./data-vol/vep-cache:/home/iobio/workdir/vep-cache:ro
    - ./data-vol/data:/home/iobio/workdir/data:ro
phenolyzer:
  image: qiaoy/iobio.phenolyzer:v2.3
